<?php

namespace ContainerXKEFeeV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDrivemanager_DropFileInterfaceService extends DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer
{
    /**
     * Gets the public 'drivemanager.DropFileInterface' shared autowired service.
     *
     * @return \DriveManager\Infrastructure\DriveProvider\DropFileNextcloud
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Service/DropFile/DropFileInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/DriveProvider/DropFileNextcloud.php';

        return $container->services['drivemanager.DropFileInterface'] = new \DriveManager\Infrastructure\DriveProvider\DropFileNextcloud('https://nuage.logipro.com/owncloud/remote.php/dav/', 'romain.malosse@logipro.com', 'AlFi5GoZI^');
    }
}
