openapi: 3.1.0
info:
  title: DriveManager API
  version: 1.0.0
servers:
  - url: http://172.17.0.1:11180/api/v1
    description: test
paths:
  /dropFile/dropFile:
    post:
      summary: Deposit a file into the directory
      operationId: dropFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                  description: Unique identifier for the file
                  example: UnIdDeTest
                fileToDeposit:
                  type: string
                  description: Name of the file to be deposited
                  example: ATestingFile.txt
                filePathToDirectory:
                  type: string
                  description: Path to the directory where the file will be deposited
                  example: Test/
                fileDate:
                  type: string
                  description: Date of the file
                  example: 2024-06-05T10:30:00
                fileContent:
                  type: string
                  description: Content of the file
                  example: Some content
                driver:
                  type: string
                  description: Name of the driver to handle the file deposit
                  example: NextCloud
      responses:
        '201':
          description: File successfully deposited
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the file deposit was successful
                    example: true
                  errorCode:
                    type: string
                    description: Name of the exception class if any error occurs
                    example: null
                  message:
                    type: string
                    description: Message associated with the response
                    example: File deposited successfully
                  data:
                    type: object
                    description: Data related to the deposited file
                    properties:
                      fileId:
                        type: string
                        example: UnIdDeTest
                      fileToDeposit:
                        type: string
                        example: testfile.txt
                      filePathToDirectory:
                        type: string
                        example: Test/
                      fileDate:
                        type: string
                        example: 2024-06-06 07:41:39.417432
                      fileContent:
                        type: string
                        example: This is a test file content
                      driver:
                        type: string
                        example: FileSysteme