<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQYADwQv\DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQYADwQv/DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQYADwQv.legacy');

    return;
}

if (!\class_exists(DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQYADwQv\DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, false);
}

return new \ContainerQYADwQv\DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer([
    'container.build_hash' => 'QYADwQv',
    'container.build_id' => '6bfb031a',
    'container.build_time' => 1717484549,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQYADwQv');
