<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerODO7qLU\DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerODO7qLU/DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerODO7qLU.legacy');

    return;
}

if (!\class_exists(DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, false)) {
    \class_alias(\ContainerODO7qLU\DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, false);
}

return new \ContainerODO7qLU\DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer([
    'container.build_hash' => 'ODO7qLU',
    'container.build_id' => '4f247bc8',
    'container.build_time' => 1717485239,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerODO7qLU');
