<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDoIGYeK\DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDoIGYeK/DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDoIGYeK.legacy');

    return;
}

if (!\class_exists(DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDoIGYeK\DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer::class, false);
}

return new \ContainerDoIGYeK\DriveManager_Infrastructure_Shared_Symfony_KernelTestDebugContainer([
    'container.build_hash' => 'DoIGYeK',
    'container.build_id' => '54393206',
    'container.build_time' => 1717598989,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDoIGYeK');
