<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8jOUTnm\DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8jOUTnm/DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer.php') {
    touch(__DIR__.'/Container8jOUTnm.legacy');

    return;
}

if (!\class_exists(DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, false)) {
    \class_alias(\Container8jOUTnm\DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer::class, false);
}

return new \Container8jOUTnm\DriveManager_Infrastructure_Shared_Symfony_KernelTestContainer([
    'container.build_hash' => '8jOUTnm',
    'container.build_id' => 'af9fc4a1',
    'container.build_time' => 1717599884,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8jOUTnm');
