<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZbaCWaq\DriveManager_Infrastructure_Shared_Symfony_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZbaCWaq/DriveManager_Infrastructure_Shared_Symfony_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZbaCWaq.legacy');

    return;
}

if (!\class_exists(DriveManager_Infrastructure_Shared_Symfony_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZbaCWaq\DriveManager_Infrastructure_Shared_Symfony_KernelDevDebugContainer::class, DriveManager_Infrastructure_Shared_Symfony_KernelDevDebugContainer::class, false);
}

return new \ContainerZbaCWaq\DriveManager_Infrastructure_Shared_Symfony_KernelDevDebugContainer([
    'container.build_hash' => 'ZbaCWaq',
    'container.build_id' => '1b18ee6e',
    'container.build_time' => 1717599485,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZbaCWaq');
