<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'DropFile' => [[], ['_controller' => 'DriveManager\\Infrastructure\\Api\\V1\\DropFileController::dropFile'], [], [['text', '/api/v1/dropFile/dropFile']], [], [], []],
    'DriveManager\Infrastructure\Api\V1\DropFileController::dropFile' => [[], ['_controller' => 'DriveManager\\Infrastructure\\Api\\V1\\DropFileController::dropFile'], [], [['text', '/api/v1/dropFile/dropFile']], [], [], []],
];
